=== LuisRamos99/PRI2020/TPC2/project_record.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project (title,body,date)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!ELEMENT body (header,workteam,abstract,deliverables)>


<!ELEMENT header (key_name,title,subtitle?,date,date,supervisor)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor url CDATA #REQUIRED >
<!ELEMENT key_name (#PCDATA)>


<!ELEMENT workteam (elem+)>
<!ELEMENT elem (name,mail?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ATTLIST mail url CDATA #REQUIRED >


<!ELEMENT abstract (paragraph)+>
<!ELEMENT paragraph (text|bold|italic|underline|link)*>
<!ELEMENT text (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT link (internal_link|external_link)>
<!ELEMENT internal_link (#PCDATA)>
<!ATTLIST internal_link url CDATA #REQUIRED >
<!ELEMENT external_link (#PCDATA)>
<!ATTLIST external_link url CDATA #REQUIRED >


<!ELEMENT deliverables (link)*>


<!--

Subtitulo não é obrigatório.
Workteam composta por 1 ou + elementos, cada elemento contém nome obrigatório.
Abstract é uma lista de paragrafos.
Deliverables é uma lista de links.

-->

=== LuisRamos99/PRI2020/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "project_record.dtd">
<project>
    <title></title>
    <body>
        <header>
            <key_name></key_name>
            <title>titulo</title>
            <date></date>
            <date></date>
            <supervisor url=""></supervisor>
        </header>
        <workteam>
            <elem>
                <name></name>
            </elem>
        </workteam>
        <abstract>
            <paragraph></paragraph>
        </abstract>
        <deliverables>
            <link url=""></link>
        </deliverables>
    </body>
    <date></date>
</project>

=== LuisRamos99/PRI2020/TPC2/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "project_record.dtd">
<project>
    <title>Project Record</title>
    <body>
        <header>
            <key_name>Project Record - TP2</key_name>
            <title>Trabalho Pratico 2</title>
            <date>22 Outubro 2020</date>
            <date>24 Outubro 2020</date>
            <supervisor url="http://www4.di.uminho.pt/~jcr/">
                Jos√© Carlos Ramalho
            </supervisor>
        </header>
        <workteam>
            <elem>
                <name>Luis Miguel Arieira Ramos</name>
            </elem>
        </workteam>
        <abstract>
            <paragraph>
                Por <bold>preencher</bold>
            </paragraph>
        </abstract>
        <deliverables>
            <link>
                <external_link url="www.gmail.com">
                    Gmail
                </external_link>
            </link>
        </deliverables>
    </body>
    <date>2020</date>
</project>
