=== LuisRamos99/PRI2020/TPC4/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (header,workteam,abstract,deliverables) >


<!ELEMENT header (key_name,title,subtitle?,bdate,edate,supervisor)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor url CDATA #IMPLIED >
<!ELEMENT bdate (#PCDATA)>
<!ELEMENT edate (#PCDATA)>
<!ELEMENT key_name (#PCDATA)>


<!ELEMENT workteam (elem+)>
<!ELEMENT elem (name, mail)>
<!ATTLIST elem num ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mail (#PCDATA)>


<!ELEMENT abstract (p)+>
<!ELEMENT p (#PCDATA|b|i|u|link)*>
<!ELEMENT b (#PCDATA|i|u|link)*>
<!ELEMENT i (#PCDATA|b|u|link)*>
<!ELEMENT u (#PCDATA|i|b|link)*>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link url CDATA #REQUIRED >


<!ELEMENT deliverables (link)+>

=== LuisRamos99/PRI2020/TPC4/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <header>
        <key_name>Project Record - TP4</key_name>
        <title>Trabalho Pratico 4</title>
        <bdate>05 Novembro 2020</bdate>
        <edate>08 Novembro 2020</edate>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">
            José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <elem num="A83930">
            <name>Luis Miguel Arieira Ramos</name>
            <mail>a83930@alunos.uminho.pt</mail>
        </elem>
    </workteam>
    <abstract>
        <p>Este <b>TPC4</b> consistiu na criação de um servidor em <i>node</i> de modo a receber pedidos e a responder aos mesmos.</p>
    </abstract>
    <deliverables>
        <link url=""></link>
    </deliverables>
</pr>
